FROM            python:3.11-slim

ENV             PYTHONUNBUFFERED=1
ENV             LANGUAGE en_US.UTF-8
ENV             PROJECTPATH=/app

RUN             set -x \
                && apt update -qq \
                && apt install -y --no-install-recommends libpq-dev binutils curl \
                && apt purge -y --auto-remove \
                && rm -rf /var/lib/apt/lists/*

RUN             mkdir -p ${PROJECTPATH}

RUN             curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 - \
                && cd /usr/local/bin \
                && ln -s /etc/poetry/bin/poetry \
                && poetry config virtualenvs.create false

WORKDIR         ${PROJECTPATH}


COPY            poetry.lock pyproject.toml ${PROJECTPATH}
COPY            sqlmodel_dist/sqlmodel-0.0.22-py3-none-any.whl ${PROJECTPATH}/sqlmodel_dist/
RUN             poetry install --no-root
COPY            . ${PROJECTPATH}



ENV             PYTHONPATH=/app


